version: '3.8'

services:
  eureka-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-service
    image: loubna/eureka-service:v1
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eureka-service
      - SERVER_PORT=8761
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
