version: '3.8'

networks:
  spring-net:

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: TitreDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net

  titre_service:
    image: loubna/titre:v1
    container_name: titre_service
    depends_on:
      - postgres
      - eureka-server
    environment:
      SPRING_APPLICATION_NAME: titre-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/TitreDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    ports:
      - "8080:8080"
    networks:
      - spring-net

  eureka-server:
    image: loubna/eureka-service:v1
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-net

volumes:
  postgres_data:
