apiVersion: v1
kind: Service
metadata:
  name: titre-service-svc
spec:
  selector:
    app: titre-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  clusterIP: None  # Permet d'accéder au service à partir du cluster
---
