version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - my_network

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "9999:9999"
    depends_on:
      - eureka-server
    networks:
      - my_network

  client-service:
    build:
      context: ./client
    container_name: client-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - my_network

  titre-service:
    build:
      context: ./titre
    container_name: titre-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - my_network

  transaction-service:
    build:
      context: ./transaction
    container_name: transaction-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
