apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  clusterIP: None  # Permet d'accéder au service de l'intérieur du cluster
---
