apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: loubna523/gateway:v1
          ports:
            - containerPort: 9999
          env:
            - name: SPRING_APPLICATION_NAME
              value: "gateway"
            - name: SERVER_PORT
              value: "9999"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "localhost"
            - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
              value: "true"
            - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID
              value: "true"
            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "true"
            - name: SPRING_CLOUD_LOADBALANCER_RIBBON_ENABLED
              value: "false"
          imagePullPolicy: Always
---
