version: '3.8'

networks:
  spring-net:
    driver: bridge

services:
  # Eureka Server
  eureka-service:
    image: loubna/eureka-service:v1
    container_name: eureka-service
    ports:
      - "8761:8761"
    networks:
      - spring-net

  # Client Service
  client-service:
    image: loubna/client:v1
    container_name: client-service
    depends_on:
      - eureka-service
      - postgres_db
      - kafka
    environment:
      SPRING_APPLICATION_NAME: client-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-service:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/ClientDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 9090
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - spring-net

  # PostgreSQL Database
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ClientDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - spring-net

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - spring-net

volumes:
  postgres_data:
