version: '3.8'

networks:
  my_network:

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: TransactionDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  transaction_service:
    image: loubna/transaction:v1
    container_name: transaction_service
    depends_on:
      - postgres
    environment:
      SPRING_APPLICATION_NAME: Transaction-Service
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/TransactionDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8082
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    ports:
      - "8082:8082"
    networks:
      - my_network

volumes:
  postgres_data:
