apiVersion: v1
kind: Service
metadata:
  name: transaction-service-svc
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  clusterIP: None  # Permet d'accéder au service à partir du cluster
---